# Generated by Django 4.0.4 on 2022-05-10 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='estado',
            new_name='estados',
        ),
    ]
