# Generated by Django 4.0.4 on 2022-05-10 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0002_rename_estado_producto_estados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='estados',
            new_name='estado',
        ),
    ]
