# Generated by Django 4.0.4 on 2022-05-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0003_rename_estados_producto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
