# Generated by Django 4.0.4 on 2022-05-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0004_alter_producto_stock_delete_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
