# Generated by Django 4.0.4 on 2022-05-14 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0005_producto_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenproducto',
            old_name='Producto',
            new_name='producto',
        ),
    ]
