# Generated by Django 4.0.4 on 2022-05-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0006_rename_producto_imagenproducto_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria_producto',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
