# Generated by Django 4.0.4 on 2022-05-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0007_categoria_producto_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria_producto',
            old_name='nombre_categ',
            new_name='nombre',
        ),
    ]
