# Generated by Django 4.0.4 on 2022-05-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0010_rename_nombre_categ_categoria_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria_producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
