# Generated by Django 4.0.4 on 2022-05-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0012_size_producto_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='medidas',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
