# Generated by Django 4.0.4 on 2022-05-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0013_size_medidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto_size',
            name='talla',
        ),
        migrations.AddField(
            model_name='producto_size',
            name='talla',
            field=models.ManyToManyField(to='indexapp.size'),
        ),
    ]
