# Generated by Django 4.0.4 on 2022-05-31 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0014_remove_producto_size_talla_producto_size_talla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='medidas',
            new_name='detalles',
        ),
    ]
