# Generated by Django 4.0.5 on 2022-07-24 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0015_rename_medidas_size_detalles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto_size',
        ),
        migrations.DeleteModel(
            name='size',
        ),
    ]
