# Generated by Django 4.0.5 on 2022-07-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
