# Generated by Django 4.0.5 on 2022-07-15 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indexapp', '0015_rename_medidas_size_detalles'),
        ('shopping_cart', '0002_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_ListaP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lista_Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.estado_listap')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexapp.producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
