# Generated by Django 4.0.5 on 2022-08-06 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0005_direccion_ticket_lista_productos_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='domicio',
            new_name='domicilio',
        ),
        migrations.RenameField(
            model_name='direccion',
            old_name='intrucciones',
            new_name='instrucciones',
        ),
        migrations.RemoveField(
            model_name='lista_productos',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
