# Generated by Django 4.0.5 on 2022-08-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0006_rename_domicio_direccion_domicilio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='estado',
            field=models.BooleanField(null=True),
        ),
    ]
